name: Upload build to Syn

on:
  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      # Must checkout first, otherwise it would show empty folder, see https://github.com/actions/checkout
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      # Modify `master` to valid version, see https://github.com/marketplace/actions/action-rsync
      - uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{secrets.HOST}}
          KEY: ${{secrets.SSH_KEY}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USERNAME}}
          SOURCE: build/
          TARGET: /volume1/homes/akme/no1yz.art/build/
          VERBOSE: true
      - uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{secrets.HOST}}
          KEY: ${{secrets.SSH_KEY}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USERNAME}}
          SOURCE: node_modules/
          TARGET: /volume1/homes/akme/no1yz.art/node_modules/
          VERBOSE: true
      - uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{secrets.HOST}}
          KEY: ${{secrets.SSH_KEY}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USERNAME}}
          SOURCE: package.json
          TARGET: /volume1/homes/akme/no1yz.art/package.json
          VERBOSE: true
